name: MRPGNPC
author: MuffinHeadANDReiyans
main: com.muffinhead.MRPGNPC.MRPGNPC
load: POSTWORLD
api: "1.0.8"
version: "1.0.0"
commands:
  mrn:
    description: "mrn main command"
    permission: commands.muffinhead.MRPGNPC
  刷怪:
    description: "MRPGNPC刷怪指令"
    permission: commands.muffinhead.MRPGNPC
permissions:
  commands.muffinhead.MRPGNPC:
    default: op